server:
  port: 9080

spring:
  application:
    name: dzz-zcsc

  data:
    mongodb:
      host: 47.92.212.198
      database: zcsc
      username: zcsc
      password: zcsc!@#456
      port: 27017


file:
  upload:
    path: /data/files/
  server:
    path: http://img.zhencangys.com/