server:
  port: 9080

spring:
  application:
    name: dzz-zcsc
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 20BM


file:
  upload:
    path: /data/files/
  server:
    path: http://img.zhencangys.com/